name: CI/CD

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

env:
  NODE_VERSION: '20.17.0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Code Linting
      run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Unit Testing
      run: yarn run test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Building
      run: yarn run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  release:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures all tags are fetched

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Tag Presence
        id: get-tag
        run: |
          TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
          if [ -n "$TAG" ]; then
            echo "tag=${TAG}" >> $GITHUB_OUTPUT
            echo "has_tag=true" >> $GITHUB_OUTPUT
          else
            echo "has_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Check Alpha Release
        id: check-alpha
        if: steps.get-tag.outputs.has_tag == 'true'
        run: |
          if [[ ${{ steps.get-tag.outputs.tag }} == *"-alpha"* ]]; then
            echo "is_alpha=true" >> $GITHUB_OUTPUT
          else
            echo "is_alpha=false" >> $GITHUB_OUTPUT
          fi

      - name: Display warning if no tag
        if: steps.get-tag.outputs.has_tag != 'true'
        run: |
          echo "::warning::No tag found for the current commit. The release will not be created."
          echo "To create a release, please ensure you've created and pushed a tag for this commit."

      - name: Use Node.js
        if: steps.get-tag.outputs.has_tag == 'true' && (steps.extract_branch.outputs.branch == 'master' || steps.check-alpha.outputs.is_alpha)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Release
        uses: ncipollo/release-action@v1
        if: steps.get-tag.outputs.has_tag == 'true'  && (steps.extract_branch.outputs.branch == 'master' || steps.check-alpha.outputs.is_alpha)
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ steps.get-tag.outputs.tag }}
          prerelease: ${{ steps.check-alpha.outputs.is_alpha }}
